version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: marketplace_db
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    command:
      - "migrate"
      - "-baselineOnMigrate=true"
    volumes:
      - ./s2/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/marketplace_db
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: qwerty007
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: marketplace

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data: